### ISSUE TITLE
hickuphh3 - Deposit queue can be bricked if `relayerFee` is increased

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#1]
hickuphh3

medium

# Deposit queue can be bricked if `relayerFee` is increased

## Summary
Minting from the deposit queue could be bricked if there is an increase to the `relayerFee`.

## Vulnerability Detail
The `relayerFee` can only be updated by the timelocker. Given the delay to update this parameter, an expected increase to the `relayerFee` can be frontrun by a queue deposit equal to the current `relayerFee`.

Attempting to mint the deposit reverts since the asset amount will be smaller than the relayer fee.

```solidity
_mintShares(
  queue[i].receiver,
  _epochId,
  queue[i].assets - relayerFee
);
```

Because the deposit queue is FILO, all prior deposits cannot be processed.

## Impact
Deposit queue may not be processed if an adversary is able to frontrun the execution of the relayer fee increase.

Another way of viewing the issue is that an adversary can prevent the `relayerFee` from ever increasing by depositing an amount equal to the current `relayerFee`.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L334-L338

## Tool used
Manual Review

## Recommendation
Consider checking that the deposit queue lengths are zero in `changeRelayerFee()`.

P.S. `getDepositQueueLenght()` and `getRolloverQueueLenght()` have incorrect spelling.

**Comment by 3xHarry** [comment]
acknowledged

**Comment by 3xHarry** [comment]
fix PR: https://github.com/Y2K-Finance/Earthquake/pull/142

**Comment by RobocopSR** [comment]
Escalate for 10 USDC

It is a valid low/info issue. From sherlock docs:

"Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? It would not count if the DOS, etc. lasts a known, finite amount of time <1 year. If it will result in funds being inaccessible for >=1 year, then it would count as a loss of funds and be eligible for a Medium or High designation."

Also, currently Arbitrum [does not have](https://developer.arbitrum.io/faqs/gas-faqs#q-mempool) a mempool, so the chances of front-running are very low.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> It is a valid low/info issue. From sherlock docs:
> 
> "Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? It would not count if the DOS, etc. lasts a known, finite amount of time <1 year. If it will result in funds being inaccessible for >=1 year, then it would count as a loss of funds and be eligible for a Medium or High designation."
> 
> Also, currently Arbitrum [does not have](https://developer.arbitrum.io/faqs/gas-faqs#q-mempool) a mempool, so the chances of front-running are very low.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low
The relayerFee can be rolled back and there is no DOS anymore. 
Also escalation raises a valid point about frontrunning in Arbitrum.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low
> The relayerFee can be rolled back and there is no DOS anymore. 
> Also escalation raises a valid point about frontrunning in Arbitrum. 
> 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
