### ISSUE TITLE
bulej93 - rollovers dont pay deposit fees

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#102]
bulej93

high

# rollovers dont pay deposit fees

## Summary
in the function mintRollovers there is no deduction of depositFees
## Vulnerability Detail
when a vault win the users have the option of enrolling into a rollover for the next epoch, if you invest in the rollover you are to pay a relayer fee as per the documentation but also you are suppose to pay the deposit fee. the relayer fee is charged but the deposit fee never is
## Impact
the protocol may lose fees 
## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L436
## Tool used

Manual Review

## Recommendation
deduct deposit fees befofe rolling over

**Comment by 3xHarry** [comment]
dup https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/298

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/298
