### ISSUE TITLE
roguereddwarf - Carousel: rollover queue feature can forever be blocked when malicious user gets added to USDC blacklist

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#109]
roguereddwarf

medium

# Carousel: rollover queue feature can forever be blocked when malicious user gets added to USDC blacklist

## Summary
USDC has a blacklist. A user that is added to the blacklist (e.g. by performing malicious actions with his address) cannot receive USDC.
USDC transfers to his address revert.

According to the contest page, the protocol supports USDC:
![2023-03-21_09-23](https://user-images.githubusercontent.com/118631472/226552188-7b599bcc-d378-4a0b-a975-54400306d9d7.png)

If the `emissionsToken` is USDC this can cause a problem.

A malicious user can get added to the USDC blacklist and put an element into the rollover queue.

The rollover queue processes all elements from head to tail.
So the rollover queue will become completely useless as it can never get past the malicious element.
Only the user can remove the bad element and when he chooses not to remove it, the rollover queue becomes permanently unusable.

Other users can remove their own queued items from the rollover queue so there are no funds lost however the queue feature which is important for the protocol is permanently blocked.

## Vulnerability Detail
This is the vulnerable code:
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L420-L425

If USDC is used as emissions token and the receiver is added to the blacklist the transfer reverts.

## Impact
The rollover queue can become unusable forever.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L361-L459

## Tool used
Manual Review

## Recommendation
Transfers that revert should be skipped and potentially the element should be removed from the rollover queue.

**Comment by 3xHarry** [comment]
acknowledged!

**Comment by dmitriia** [comment]
Invalid, emission token is protocol owned token, not stablecoin

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC. this is a high finding or at least a medium finding. 

the scope of the ERC20 token is 

ERC20: [WETH, USDC, Y2K]

there is no documentation that says the mission token is the protocol's own token.

So during the auditing, the auditor is allowed to use different tokens to challenge the code.

We are using the assumption that when the emission token is USDC, it is easy to DOS the rollover queue.

This issue has been historically rewarded as high.

https://github.com/sherlock-audit/2022-11-opyn-judging/issues/219

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC. this is a high finding or at least a medium finding. 
> 
> the scope of the ERC20 token is 
> 
> ERC20: [WETH, USDC, Y2K]
> 
> there is no documentation that says the mission token is the protocol's own token.
> 
> So during the auditing, the auditor is allowed to use different tokens to challenge the code.
> 
> We are using the assumption that when the emission token is USDC, it is easy to DOS the rollover queue.
> 
> This issue has been historically rewarded as high.
> 
> https://github.com/sherlock-audit/2022-11-opyn-judging/issues/219
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by dmitriia** [comment]
@Jiaren-tang USDC and other permissioned tokens blacklisting is a valid issue in general, but in this case emission token is protocol token only by design, which is a kind of straightforward.

**Comment by hrishibhat** [comment]
Escalation rejected

As pointed out by the Lead Judge emission token is the protocol token. 
https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/claiming-rewards#claiming-y2k-rewards

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> As pointed out by the Lead Judge emission token is the protocol token. 
> https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/claiming-rewards#claiming-y2k-rewards

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
