### ISSUE TITLE
0xChinedu - Epochs For Various Created Markets is Never Returned

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#119]
0xChinedu

medium

# Epochs For Various Created Markets is Never Returned

## Summary
The VaultFactoryV2.createEpoch() claims to return the epochIds for created markets but doesn't.
## Vulnerability Detail
The VaultFactoryV2.createEpoch() can only be called by the owner, the function claims to **"returns (uint256 epochId, address[2] memory vaults) "** when called by the owner but these values are never returned by the function as there is no return statement.
## Impact
The epochId to various markets is never returned to the owner when epochs are created.
## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L137-L169
```solidity
    function createEpoch(
        uint256 _marketId,
        uint40 _epochBegin,
        uint40 _epochEnd,
        uint16 _withdrawalFee
    ) public onlyOwner returns (uint256 epochId, address[2] memory vaults) {
        vaults = marketIdToVaults[_marketId];

        if (vaults[0] == address(0) || vaults[1] == address(0)) {
            revert MarketDoesNotExist(_marketId);
        }

        if (_withdrawalFee == 0) revert FeeCannotBe0();

        if (!controllers[IVaultV2(vaults[0]).controller()])
            revert ControllerNotSet();
        if (!controllers[IVaultV2(vaults[1]).controller()])
            revert ControllerNotSet();

        epochId = getEpochId(_marketId, _epochBegin, _epochEnd);

        _setEpoch(
            EpochConfiguration(
                _epochBegin,
                _epochEnd,
                _withdrawalFee,
                _marketId,
                epochId,
                IVaultV2(vaults[0]),
                IVaultV2(vaults[1])
            )
        );
    }
```
## Tool used

Manual Review

## Recommendation
Consider adding the proper return statement of the function.

**Comment by 3xHarry** [comment]
invalid,  `vaults = marketIdToVaults[_marketId]; ` declares the vault addresses
