### ISSUE TITLE
Delvir0 - Insufficient Chainlink feed validation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#126]
Delvir0

medium

# Insufficient Chainlink feed validation

## Summary
ControllerPeggedAssetV2.getLatestPrice has insufficient Chainlink feed validation
## Vulnerability Detail
Since there is insufficient check for stale prices, a stablecoin could depeg and return to peg if while not being pickup due to stale prices.
While pegOracle does implement a check on this, it's not sufficient: https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/oracles/PegOracle.sol#L79 (not sure if this contract is going to be used).
## Impact
Users that deposited a premium will not receive assets according to projects mechanism/ concept at depeg or other project economics could result in a loss. 
## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Controllers/ControllerPeggedAssetV2.sol#L313-L315
## Tool used

Manual Review

## Recommendation
Implement the solution that has been provided in previous audit https://github.com/code-423n4/2022-09-y2k-finance-findings/issues/61

**Comment by Delvir0** [comment]
Escalate for 10 USDC
Duplicate of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/70

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> Duplicate of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/70

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Duplicate of #70

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Duplicate of #70 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
