### ISSUE TITLE
PRAISE - Owner will have to re-queue tx before he can execute it again whenever tx fails in TimeLock.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#132]
PRAISE

medium

# Owner will have to re-queue tx before he can execute it again whenever tx fails in TimeLock.sol

## Summary
Owner will have to re-queue tx before executing it again whenever tx fails.

## Vulnerability Detail
The execute function() **deletes** the executed transaction ID **from queue** even   **before executing it** 
```solidity
        //delete tx from queue
        queued[txId] = false;
```

So if a tx should fail when executing it. The owner will have to re-queue it again before calling the execute function. Which can be stressful... owner should be able to just re-execute immediately.

## Impact
since the txId is deleted from the queue even before the transaction is executed, in a situation where the executed tx fails the owner won't be able to re-execute it immediately as the txId has already been deleted from the queue. The Owner will have to re-queue it before they can execute it via the execute() function.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/TimeLock.sol#L99-L100

## Tool used

Manual Review

## Recommendation
 delete the txId from queue only after the transaction is successful.

**Comment by 3xHarry** [comment]
the time lock is only really meant to interact with the VaultFactory and it's unlikely that there will be any outgoing calls that could fail. Also, this is a standard timelock contract template.
