### ISSUE TITLE
0xRobocop - Arbitrary number on the relayer fee condition can cause problems on tokens with few decimals

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#144]
0xRobocop

medium

# Arbitrary number on the relayer fee condition can cause problems on tokens with few decimals

## Summary

The protocol sets a `relayerFee`, this fee is paid to a 'relayer' for each `operation` when calling `mintRollovers()` and `mintDepositQueue()`, this fee can be become too costly on `underlyingAssets` with few decimals.

## Vulnerability Detail

The `relayerFee` cannot be smaller than 10_000. This is enforced on [CarouselFactory.sol](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/CarouselFactory.sol#L167) when trying to change the `relayerFee` and on the constructor of [Carousel.sol](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L52)

The reason for this is to not be able to set a too low `relayerFee`. But for ERC20 tokens with few decimals used as `underlyingAsset`  this can become too costly. For example is known that USDC and USDT both have 6 decimals, and WBTC has 8 decimals. 

## Impact

For example, if WBTC wanted to be used as `underlyingAsset` for premiums and collaterals, then the minimum `relayerFee` is 0.0001 WBTC (1 WBTC is represented as 100_000_000, 8 decimals). WBTC is trading at 27_000 usd at the time this issue was written, this will yield a `relayerFee` with a value of 2.7 usd (0.0001 * 27_000), and this fee is paid for each entry processed of the `depositQueue` or `rolloverQueue`.

Although the vulnerability does not cause a loss of funds, it can cause that any marketId (a combination of a token and a strike-price) with a too high `relayerFee` to not be used by users. As well that can be seen (from the check of the relayerFee not being too low) that the Y2K Finance team wants to find a economic balance on this parameter.

## Code Snippet

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L52

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/CarouselFactory.sol#L167
## Tool used

Manual Review

## Recommendation

When deciding on what is a too low or a too high `relayerFee` take into account the decimals the `underlyingAsset` has.

**Comment by RobocopSR** [comment]
Escalate for 10 USDC

It should be a valid medium, it breaks core assumptions about the economic mechanics of the protocol, for example WBTC markets will get disabled because of a high relayer fee.

This is not a low issue because the fix is very important for the core functionality of the protocol, this is not a mere improvement to the UX but a fix of an important economic vulnerability. 

Even if Sherlock docs states that meds and highs involves loss of funds, it does not say economic vulnerabilities should be marked as low.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> It should be a valid medium, it breaks core assumptions about the economic mechanics of the protocol, for example WBTC markets will get disabled because of a high relayer fee.
> 
> This is not a low issue because the fix is very important for the core functionality of the protocol, this is not a mere improvement to the UX but a fix of an important economic vulnerability. 
> 
> Even if Sherlock docs states that meds and highs involves loss of funds, it does not say economic vulnerabilities should be marked as low.
> 
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Sponsor comment:
> also as the markets are configured by admin each relayer fee is set based on underlying asset value and respective decimals. Potential underling asset is WETH / USDC

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> Sponsor comment:
> > also as the markets are configured by admin each relayer fee is set based on underlying asset value and respective decimals. Potential underling asset is WETH / USDC

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
