### ISSUE TITLE
yixxas - Rollovers can be DOSed by a malicious attacker by transferring away tokens that are meant to be burned

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#149]
yixxas

high

# Rollovers can be DOSed by a malicious attacker by transferring away tokens that are meant to be burned

## Summary
Rollover queue is based on a first in last out basis. In `mintRollovers()`, ERC1155 tokens are burned from users and new ones are minted. Function can be forced to revert if user does not have the required tokens to be burned for.

## Vulnerability Detail
A user can enlist for rollover with the requirement that they have sufficient balance of the ERC1155 tokens. However, after enlisting, user can transfer away the underlying ERC1155 token using `safeTransferFrom()`. This would prevent any deposits made before the malicious user in the rollover queue from executing since it will revert at this rollover.

## Impact
A malicious attacker can completely prevent rollovers from happening by this attack. They can also safely delist should they not want to continue the attack anymore, hence making this a very low cost attack.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L238-L250
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L408-L411

## Tool used

Manual Review

## Recommendation
Consider skipping a particular rollover if it does not have the required ERC1155 tokens, instead of reverting the entire queue.

**Comment by dmitriia** [comment]
It looks like `notRollingOver` does its job and this is invalid.

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L190-L196

```solidity
    function safeTransferFrom(
        address from,
        address to,
        uint256 id,
        uint256 amount,
        bytes memory data
    ) public override notRollingOver(from, id, amount) {
```

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L749-L762

```solidity
    modifier notRollingOver(
        address _receiver,
        uint256 _epochId,
        uint256 _assets
    ) {
        if (ownerToRollOverQueueIndex[_receiver] != 0) {
            QueueItem memory item = rolloverQueue[getRolloverIndex(_receiver)];
            if (
                item.epochId == _epochId &&
                (balanceOf(_receiver, _epochId) - item.assets) < _assets
            ) revert AlreadyRollingOver();
        }
        _;
    }
```

**Comment by 3xHarry** [comment]
invalid already pointed out by @dmitriia
