### ISSUE TITLE
yixxas - Relayer fee should take into consideration the number of decimals in underlying `_assets`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#151]
yixxas

high

# Relayer fee should take into consideration the number of decimals in underlying `_assets`

## Summary
Relayer fee is currently implemented as a flat fee. An amount of 10000 would mean 10000 of underlying asset is paid as fee. However, different assets have different number of decimals and this can result in fees being paid unevenly.

## Vulnerability Detail
Relayer fee is paid in both `mintDepositInQueue()` and `mintRollovers()`. This fee is paid simply by subtracting from `assets` this way `queue[i].assets - relayerFee`. We currently enforce that relayerFee must be at least 10000 units. However, USDC is 6 decimals whereas WETH is 18 decimals. At the minimum of 10000 units, it means relayer fee is $0.1. However, 10000 units of WETH is only 1e-14 ether which is much lesser than $0.1.

## Impact
Minimum relayer fee imposed is vastly different for tokens with different decimals.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L337

## Tool used

Manual Review

## Recommendation
Relayer fee should not be implemented as a flat amount, but instead consider the number of deciamls used for the underlying asset.

**Comment by 3xHarry** [comment]
This is indeed the case as 10000 is just the minimum and every market is able to configure the relayerFee individually

**Comment by dmitriia** [comment]
Valid low, WBTC based markets can be disabled in the future, as described in 144.

It's recommended to either make the hard coded limit flexible or at least reduce in `if (_data.relayerFee < 10000) revert RelayerFeeToLow()` (CarouselFactory's changeRelayerFee() and Carousel's constructor).

**Comment by yixxas** [comment]
Escalate for 10 USDC

Protocol should reconsider this issue. 10000 units is the minimum, but this amount (in terms of dollar) varies significantly for different markets. A USDC/USDT based market **cannot** configure relayerFee to be lower than $0.1. On the other hand, WETH based market would have a minimum fee of $0.000000000018 (assuming ETH price of $1800). This amount seems far too low and defeats the purpose of the minimum check.

Clearly the minimum relayer fee check has its purpose. We want to provide sufficient economic incentive for relayers. At the same time, we do not want to force the market to have to set a relayer fee that might be considered too high for certain markets (USDC/USDT). This can discourage the use of such markets.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Protocol should reconsider this issue. 10000 units is the minimum, but this amount (in terms of dollar) varies significantly for different markets. A USDC/USDT based market **cannot** configure relayerFee to be lower than $0.1. On the other hand, WETH based market would have a minimum fee of $0.000000000018 (assuming ETH price of $1800). This amount seems far too low and defeats the purpose of the minimum check.
> 
> Clearly the minimum relayer fee check has its purpose. We want to provide sufficient economic incentive for relayers. At the same time, we do not want to force the market to have to set a relayer fee that might be considered too high for certain markets (USDC/USDT). This can discourage the use of such markets.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Timelock operator is trusted to set the appropriate value for different markets.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> Timelock operator is trusted to set the appropriate value for different markets. 
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
