### ISSUE TITLE
ABA - Exact strike price does not trigger a depeg

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#191]
ABA

medium

# Exact strike price does not trigger a depeg

## Summary

By definition, the striking price is the price at which the depeg is triggered. We can see this indicated in several places of the documentation:

https://y2k-finance.gitbook.io/y2k-finance/products/earthquake/mechanics#oracle
> When the Chainlink oracle indicates that the strike price for a given vault has been hit, the epoch will end and vault will be closed. This will initiate a transfer of Risk vault deposits to the Hedge vault.

https://y2k-finance.gitbook.io/y2k-finance/products/earthquake/contracts-and-audits/system-architecture#controller
> TriggerDepeg => function that if the epoch has not ended and the oracle reports a price lower than the Vault Market strike price, will swap the Hedge Vault premium with Risk Vault, and close that epoch.

But in code the strike price is also a valid price for a depege to _not be triggered_:

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Controllers/ControllerPeggedAssetV2.sol#L64-L65
```Solidity
    if (int256(premiumVault.strike()) <= price)
        revert PriceNotAtStrikePrice(price);
```

## Vulnerability Detail

See Summary

## Impact

Strike price dictates which users lose funds because of the depeg, as such, any small change can have a significant impact.

## Code Snippet

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Controllers/ControllerPeggedAssetV2.sol#L64-L65

## Tool used

Manual Review

## Recommendation

Change `<=` to `<` to reflect protocol logic.

**Comment by 3xHarry** [comment]
this is a design decision

**Comment by dmitriia** [comment]
Closing per comments, not an issue
