### ISSUE TITLE
warRoom - Users depositing in current epoch are forced to deposit more than relayer fee amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#207]
warRoom

medium

# Users depositing in current epoch are forced to deposit more than relayer fee amount

## Summary
Users unable to deposit with amount less than relayerfee despite being in deposit window.
## Vulnerability Detail

There is `minRequiredDeposit` modifier in the deposit and depositEth function of the Carousel contract

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L78-L89

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L736-L742
Which tries to ensure that the requested deposit amount is greater than the relayerFee. That is justified only for the users trying to deposit outside of the deposit window. 

But users trying to deposit in the current epoch should be able to deposit any amount, even an amount less than relayerFee.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L736-L742

## Tool used

Manual Review
## Recommendation 
- Implement a check which ensures that the above check is only applied for users with `epoch Id 0` inside minRequiredDeposit() modifier.

**Comment by nemveer** [comment]
Escalate for 10 USDC

We believe that this is a valid issue.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> We believe that this is a valid issue.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue. The code seems to be working as expected. Users not able to deposit lesser than relayerFee is not a valid high/medium

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid issue. The code seems to be working as expected. Users not able to deposit lesser than relayerFee is not a valid high/medium

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
