### ISSUE TITLE
warRoom - changeTreasury() function will always update vault's treasury address to factory's treasury address

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#219]
warRoom

medium

# changeTreasury() function will always update vault's treasury address to factory's treasury address

## Summary
When the **changeTreasury()** function of vaultFactory is called via Timelocker to change the vault's treasury address, it is updated to the vault factory's native treasury state variable instead of the argument provided.

As a result, **depositFee** will be transferred to the wrong treasury.
## Vulnerability Detail
**Where**: [VaultFactoryV2](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L228-L246)

As shown in the snippet, the argument passed to the vault.setTreasury() function is treasury instead of _treasury.

## Impact
- Inside deposit() function of carousel contract, the deposit fee is transferred to the vault's treasury, which is an incorrect address.
- There is no way to **update** the treasury address in a vault.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L228-L246

## Tool used
Manual Review

## Recommendation
Correct the typo from **treasury** to **_treasury**

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/435
