### ISSUE TITLE
Respx - A slow response or a denial of service attack could prevent the resolution of a brief depeg

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#228]
Respx

high

# A slow response or a denial of service attack could prevent the resolution of a brief depeg

## Summary
Depeg events check the current price of the token only. If the token depegs for a brief period of seconds or minutes, it might be possible to miss resolving the depeg event if the oracle price updates before the transaction to trigger the depeg is processed.

## Vulnerability Detail
Depegs are triggered by any account calling `ControllerPeggedAssetV2.triggerDepeg()`. Within this function, the latest token price is checked and compared to the strike price on [line 62](https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/Controllers/ControllerPeggedAssetV2.sol#L62-L65). If this current price has not reached the strike price, the transaction reverts. 

The transaction also reverts on [line 73](https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/Controllers/ControllerPeggedAssetV2.sol#L73) if the epoch has ended, regardless of what the strike price may have been in the final blocks of the epoch.

This system for resolving depegs will function if the depeg event lasts for hours or more, but if the depeg lasts for only a single block, or a small number of blocks, or occurs right before the end of the epoch, then anything which delays calls to `ControllerPeggedAssetV2.triggerDepeg()` would effectively cancel the depeg entirely. There are several ways this might occur:

- A network attack against the blockchain itself could cause downtime.
- An unrelated event could cause an interruption in general network connectivity.
- Collusion with block producers could exclude transactions which call `ControllerPeggedAssetV2.triggerDepeg()`.
- An unexpected sudden surge in network demand, such as occurred previously with the launch of certain NFT projects, could push gas fees up suddenly, trapping calls to `ControllerPeggedAssetV2.triggerDepeg()` in the mempool until gas fees drop again.

As can be seen, it is possible that the depeg event could be prevented from resolving either by intentional attacks or by unfortunate timing.

## Impact

In this situation, clearly the premium users would lose their claim on the contents of the collateral vault.

It is important to note, when considering impact, that a user who has bought insurance against a depeg event could potentially suffer serious financial losses from even a twenty second depeg, or a depeg which begins twenty seconds before the end of the epoch. If they have leveraged positions elsewhere which are liquidated at the strike price, then the insurance they purchased through the Y2K protocol could be essential for their solvency. Loss of compensation from the Y2K system should not just be considered as a missed gain, therefore, but as a potentially serious loss.

## Code Snippet
https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/Controllers/ControllerPeggedAssetV2.sol#L62-L65
```Solidity
        int256 price = getLatestPrice(premiumVault.token());

        if (int256(premiumVault.strike()) <= price)
            revert PriceNotAtStrikePrice(price);
```

https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/Controllers/ControllerPeggedAssetV2.sol#L73
```Solidity
        if (block.timestamp > uint256(epochEnd)) revert EpochExpired();
```

## Tool used

Manual Review

## Recommendation
Add a timestamp parameter to `ControllerPeggedAssetV2.triggerDepeg()` to allow checking the price at a previous point within the current active epoch. Also, consider adding a grace period at the end of an epoch when this function could still be called.

**Comment by dmitriia** [comment]
Duplicate of #422
