### ISSUE TITLE
Respx - Unintuitive code behaviour for oracles when creating a new market

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#230]
Respx

medium

# Unintuitive code behaviour for oracles when creating a new market

## Summary
When a new market is created, the oracle parameter could be silently ignored. If it is used, the oracle is updated for all markets but no event is emitted. These two factors could easily lead to mistakes or disruption.

## Vulnerability Detail
In calls to `VaultFactoryV2.createNewMarket()`, if a new oracle is defined in `_marketCalldata.oracle`, it will be silently ignored if another oracle is already set for the relevant token.
If the new oracle is used, no event is emitted, even though there is an `OracleChanged` event used in the `changeOracle()` function.
If an oracle is provided in the function call arguments, and an oracle is already defined for the token in `tokenToOracle[_marketCalldata.token]` then there is likely human error and the transaction should revert.

## Impact
This unintuitive code behaviour could lead to a market being created with the belief that a particular oracle is being used when in fact an old oracle is being used. The old oracle might have become unreliable. This could lead to misconfigurations leading to unexpected depegs or depegs failing to trigger when they should. 

## Code Snippet
https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/VaultFactoryV2.sol#L72-L74
```Solidity
        if (tokenToOracle[_marketCalldata.token] == address(0)) {
            tokenToOracle[_marketCalldata.token] = _marketCalldata.oracle;
        }
```
https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/VaultFactoryV2.sol#L318
```Solidity
        emit OracleChanged(_token, _oracle);
```

## Tool used

Manual Review

## Recommendation
If an oracle is provided in the function call arguments, and an oracle is already defined for the token in `tokenToOracle[_marketCalldata.token]` then there is likely human error and the transaction should revert. If no existing oracle is defined, then a new oracle is of course required, and the event `OracleChanged` should be emitted.

**Comment by 3xHarry** [comment]
Changing the oracle already deployed markets and potentially ongoing epochs, is a crucial operation that has to go through timelock contract.

**Comment by dmitriia** [comment]
Looks like there is only some operational risk here (while setup described is suitable from operational viewpoint, e.g. for calling with the same Oracle), so it looks like best practices suggestion, closing.
