### ISSUE TITLE
cccz - Incorrect parameters for the Withdraw event in Carousel.mintRollovers

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#273]
cccz

medium

# Incorrect parameters for the Withdraw event in Carousel.mintRollovers

## Summary
Incorrect parameters for the Withdraw event in Carousel.mintRollovers
## Vulnerability Detail
The parameter of the Withdraw event in Carousel.mintRollovers should use the epochID of the queue, not the current epochID
## Impact
The parameter of the Withdraw event in Carousel.mintRollovers should use the epochID of the queue, not the current epochID
## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L428-L435
## Tool used

Manual Review

## Recommendation
```diff
                    emit Withdraw(
                        msg.sender,
                        queue[index].receiver,
                        queue[index].receiver,
-                       _epochId,
+                      queue[index].epochId,
                        queue[index].assets,
                        entitledShares
                    );

```

**Comment by dmitriia** [comment]
Setting this as a valid low with no funds at risk
