### ISSUE TITLE
Ch_301 - Users could avoid the paying `depositFee`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#298]
Ch_301

medium

# Users could avoid the paying `depositFee`

## Vulnerability Detail
In case there is an epoch `epoch X` still during the deposit period. Users could avoid paying [depositFee](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L479-L489) (in case `relayerFee`<`depositFee`)
 
Just by using the queue deposit and then relayers will invoke `mintDepositInQueue()` for `epoch X` and the user will only pay `relayerFee` 

## Impact
Users could avoid the paying `depositFee`

## Tool used

Manual Review

## Recommendation
If there is an epoch still during the deposit period users should only use the direct deposit

**Comment by 3xHarry** [comment]
dup of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/75

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/75

**Comment by Ch-301** [comment]
Escalate for 10 USDC

This is a duplicate of #75 
The Sponsors confirm that

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is a duplicate of #75 
> The Sponsors confirm that

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #75

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #75 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
