### ISSUE TITLE
spyrosonic10 - Lack of `proof of depeg` will results in premium vault losing assets

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#305]
spyrosonic10

high

# Lack of `proof of depeg` will results in premium vault losing assets

## Summary
Once vaults are configured for epoch and epoch is started then epoch will conclude with one of the two possible outcomes: either `depeg` will be observed during epoch or no depeg. Based on the outcome of epoch either `premium` side or `collateral` side will make profit.

There are scenarios when `depeg` will not be recorded and that will ended favoring the other, `collateral` vault, side

## Vulnerability Detail
Just for clarity, as far as vaults are concerned, `depeg` is defined as `current price < strike price`.

There are at least 2 specific cases when the above scenario can be observed.
- strike price is met and `triggerDepeg` is called but transaction is not settled for a few blocks and when it is settled price > strike.
- strike price is met during the last minutes/seconds of epoch. Either there will not be enough time to `triggerDepeg` or the transaction will not settle on time.

These scenarios will result in `premium` vaults losing their assets even though depeg was observed and recorded on blockchain.

## Impact
`premium` vault has risk of losing all assets due to lack of `proof of depeg` in protocol. It is important to note that there will be `proof of depeg` available on blockchain to dispute the outcome of this epoch.

## Code Snippet
`triggerDepeg()` => [ControllerPeggedAssetV2.sol#L51-L138](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Controllers/ControllerPeggedAssetV2.sol#L51-L138)

## Tool used
Manual Review

## Recommendation
Consider adding some mechanism where anyone can provide `proof of depeg` for any given epoch and this proof can be validated on-chain as part of `triggerDepeg`.
This will ensure few things
- Inclusion of users/community in making decision as public has chance to provide proof of depeg
- There will be no dispute on outcome
- A depeg which lasts only a few blocks can be validated. More business logic can be added around this.

**Comment by dmitriia** [comment]
Considering dup of #422 along with 462/228/71.
Note that this set of issues there aren’t the strict dups in the technical sense, but point to the very same root issue and all are borderline low/medium, so packing them in one valid medium.

**Comment by dmitriia** [comment]
Duplicate of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/422
