### ISSUE TITLE
xyzbtchunt - No check for active Arbitrum Sequencer in Oracle price

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#306]
xyzbtchunt

medium

# No check for active Arbitrum Sequencer in Oracle price

## Summary
Chainlink recommends that all L2 oracles consult the Sequencer Uptime Feed to ensure that the prior sequencer trusts the data returned by the oracle. This check is implemented in ArbiChainlinkOracle.sol

## Vulnerability Detail
If the Arbitrum Sequencer goes down, the oracle data won't be updated, and can therefore become basic. However, users can continue to interact with the protocol directly through contracts
As a result, users may be able to use the protocol when the oracle feed is basic. This can cause a lot of problems, but as a simple example:
A user has an account with 100 tokens, each worth 1 ETH, and no loans
Sequencer Arbitrum temporarily shuts down
On the way down, the price of each token drops to 0.5 ETH
A user's current account value is 50 ETH, so they should be able to borrow a maximum of 200 ETH to keep the account healthy ((200 + 50) / 200 = 1.2)
Due to the floor price the protocol published they borrowed 400 ETH ( (400 + 100) / 400 = 1.2

## Impact
If the Arbitrum sequencer goes down, the protocol will allow users to continue operating at their previous (stale) level.

``` solidity
ControllerPeggedAssetV2.sol
273:   function getLatestPrice(address _token) public view returns (int256) {
274:         (
275:             ,
276:             /*uint80 roundId*/
277:             int256 answer,
278:             uint256 startedAt, /*uint256 updatedAt*/ /*uint80 answeredInRound*/
279:             ,
280: 
281:         ) = sequencerUptimeFeed.latestRoundData();
282: 

 @> if (!isSequencerActive()) revert Errors.L2SequencerUnavailable();

283:         // Answer == 0: Sequencer is up
284:         // Answer == 1: Sequencer is down
285:         bool isSequencerUp = answer == 0;  
286:         if (!isSequencerUp) {
287:             revert SequencerDown();
288:         }
289: 
290:         // Make sure the grace period has passed after the sequencer is back up.
291:         uint256 timeSinceUp = block.timestamp - startedAt;
292:         if (timeSinceUp <= GRACE_PERIOD_TIME) {
293:             revert GracePeriodNotOver();
294:         }
295: 

```
## Code Snippet

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Controllers/ControllerPeggedAssetV2.sol#L51-L138

## Tool used

Manual Review

## Recommendation
consider add active sequencer or not active  sequencer arbitrum in oracle price
``` solidity
function isSequencerActive() internal view returns (bool) {
    (, int256 answer, uint256 startedAt,,) = sequencer.latestRoundData();
    if (block.timestamp - startedAt <= GRACE_PERIOD_TIME || answer == 1)
        return false;
    return true;
}
```

**Comment by xyzbtchunt** [comment]
Escalate for 10 USDC. I think almost similar triggerDepeg delay after the epoch end to make verify de-pegging event. 

 [Duplicate 422](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/422)

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC. I think almost similar triggerDepeg delay after the epoch end to make verify de-pegging event. 
> 
>  [Duplicate 422](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/422) 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a duplicate of #422

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a duplicate of #422 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
