### ISSUE TITLE
ShadowForce - User can burn shares and receive no assets in return

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#312]
ShadowForce

high

# User can burn shares and receive no assets in return

## Summary
User can burn his shares but receive no assets in return.
## Vulnerability Detail
In the `VaultV2.sol` contract the withdraw function burns the users share and in turn sends him assets. you can view this logic down below.
```solidity
    function withdraw(
        uint256 _id,
        uint256 _assets,
        address _receiver,
        address _owner
    )
        external
        virtual
        override(SemiFungibleVault)
        epochIdExists(_id)
        epochHasEnded(_id)
        nonReentrant
        returns (uint256 shares)
    {
        if (_receiver == address(0)) revert AddressZero();

        if (
            msg.sender != _owner &&
            isApprovedForAll(_owner, msg.sender) == false
        ) revert OwnerDidNotAuthorize(msg.sender, _owner);

        _burn(_owner, _id, _assets);

        uint256 entitledShares;

        if (epochNull[_id] == false) {
            entitledShares = previewWithdraw(_id, _assets);
        } else {
            entitledShares = _assets;
        }
        if (entitledShares > 0) {
            SemiFungibleVault.asset.safeTransfer(_receiver, entitledShares);
        }

        emit Withdraw(
            msg.sender,
            _receiver,
            _owner,
            _id,
            _assets,
            entitledShares
        );

        return entitledShares;
    }

```
This function calls into the `previewWithdraw` Function to determine the amount of shares the user is entitled to. that is seen below.
```solidity
    function previewWithdraw(uint256 _id, uint256 _assets)
        public
        view
        override(SemiFungibleVault)
        returns (uint256 entitledAmount)
    {
        // entitledAmount amount is derived from the claimTVL and the finalTVL
        // if user deposited 1000 assets and the claimTVL is 50% lower than finalTVL, the user is entitled to 500 assets
        // if user deposited 1000 assets and the claimTVL is 50% higher than finalTVL, the user is entitled to 1500 assets
        entitledAmount = _assets.mulDivDown(claimTVL[_id], finalTVL[_id]);
    }
```
The problem with this is that since `previewWithdraw` rounds down to 0, the user may burn shares and his asset that is to returned to him may be rounded down to 0 and therefore he has burned his share for no return when he should have expected a return. This is a direct loss of funds for the user. 
when finalTVL[id] > assets * claimTVL[id], the preview amount is rounded to 0.
## Impact
Because the `previewWithdraw` function rounds down instead of up, a user who attempts to withdraw will have his shares burned but he will not receive any assets in return. This is a complete loss of funds for the user.
## Code Snippet
https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/VaultV2.sol#L148-L192

https://github.com/Y2K-Finance/Earthquake/blob/736b2e1e51bef6daa6a5ecd1decb7d156316d795/src/v2/VaultV2.sol#L357-L367
## Tool used

Manual Review

## Recommendation
change 
```solidity
entitledAmount = _assets.mulDivDown(claimTVL[_id], finalTVL[_id]);
```
to 
```solidity
entitledAmount = _assets.mulDivUp(claimTVL[_id], finalTVL[_id]);
```
also add
```solidity
require(entitledAmount > 0, "0 amount of asset is not valid")
```

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC. Duplicate of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/89. 

In this report, I wrote:

> The problem with this is that since previewWithdraw rounds down to 0, the user may burn shares and his asset that is to returned to him may be rounded down to 0 and therefore he has burned his share for no return when he should have expected a return. This is a direct loss of funds for the user.
when finalTVL[id] > assets * claimTVL[id], the preview amount is rounded to 0.

In report 89, the auditor write:

> Using round-down to calculate amount of distributing emissionTokens make some emissionTokens stuck in the contract

> Note that this issue also happens for function VaultV2.previewWithdraw().

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC. Duplicate of https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/89. 
> 
> In this report, I wrote:
> 
> > The problem with this is that since previewWithdraw rounds down to 0, the user may burn shares and his asset that is to returned to him may be rounded down to 0 and therefore he has burned his share for no return when he should have expected a return. This is a direct loss of funds for the user.
> when finalTVL[id] > assets * claimTVL[id], the preview amount is rounded to 0.
> 
> In report 89, the auditor write:
> 
> > Using round-down to calculate amount of distributing emissionTokens make some emissionTokens stuck in the contract
> 
> > Note that this issue also happens for function VaultV2.previewWithdraw().

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sherlock-admin** [comment]
> Escalate for 11 USDC
> 
> I am pretty sure the rounding loss/gain would be exact 1 wei for each user. Which is insignificant.
> 
> 
> There are also 3 other issues explain the same thing but excluded. These should be awarded too if this is medium issue.
> 
> [Saeedalipoor01988 025](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/312#issue-1642825334) high L-ERC4626 rounding User will receive a smaller amount of tokens than the actual amount because of rounding down in the previewEmissionsWithdraw and previewWithdraw
> 
> [xyzbtchunt 314](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/314#issue-1642827785) medium L-ERC4626 rounding Math rounding in VaultV2.sol is not ERC4626-complicant: previewWithdraw should round up.
> 
> [ShadowForce 312](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/312) high L-ERC4626 rounding User can burn shares and receive no assets in return
> 
> Also, if author change to `mulDivUp()`, there is a good chance that the last user withdraw will be reverted, which turn this into another **high** issue. Because there was no `mulDivDown()` in deposit function (intentional I guess).
> 
> Use `mulDivDown()` here instead of `mulDivUp()` pretty reasonable since this is not ERC4626 holding only 1 asset. The vault contract act like ERC1155 holding multi token over multiple epoch.
> 
> The code author seemed quite lazy to write `balanceOf()` function to keep track of the whole epoch thing. And just let `ControllerPeggedAssetV2` just paste `totalSupply()` value directly into `VaultV2`. Just so, Vault can calculate share balance for each user based on final `totalSupply()` instead of current `balanceOf()` like `ERC4626` standard.
> 
> This seem like a fast approach as it cut down devlopment time. Otherwise code author would have use `mulDivUp()` like actual `ERC4626` solmate implementation.
> 
> 

You've deleted an escalation for this issue.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #89

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #89 
> 
> 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
