### ISSUE TITLE
spyrosonic10 - epochResolved check will fail and delay rollover in `mintRollovers`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#352]
spyrosonic10

high

# epochResolved check will fail and delay rollover in `mintRollovers`

## Summary
For any given token and strike price a market is defined and in this market there can be multiple epochs ongoing at the same time. Current logic of `mintRollovers()` will assume the given epoch is latest and check that previous(current epoch - 1) is resolved and it will work if only 1 epoch is ongoing at any given time but that is not the case as per protocol design.

## Vulnerability Detail
During `mintRollovers()` call logic verifies that a given epoch is not started and the previous epoch is resolved.
```solidity
    	// prev epoch is resolved
    	if (!epochResolved[epochs[epochs.length - 2]])
        	revert EpochNotResolved();
```
Above logic clearly does not take multiple ongoing epochs into account.

Assume a scenario where epoch1 is for 1 week, epoch2 is 2 weeks and epoch3 is 4 weeks long and all epochs are ongoing at any given time. After epoch1 is over epoch4 is created for another weekly epoch and if user(s) from epoch1 are enlisted for rollover then these users will not be rollover as logic will check if epoch3 is resolved. Users who trust `mintRollovers` to be rollover will miss epoch4 as they will not be rollover for next 3 weeks at least in this scenario

## Impact
Users will not be rolled over to the new epoch and will not be able to take advantage of rollover features.

## Code Snippet
[Carousel.sol#L361-L459](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L361-L459)

## Tool used

Manual Review

## Recommendation
Consider updating logic to handle multiple epochs.

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC

Not sure why this was excluded.
Technically multiple epochs are possible for the same token and strike price aka same marketId in Carousel.sol.
Consider this example:
- Token: DAI, Strike price: 0.99 Epoch: 7 days
- Token DAI, Strike price: 0.99 Epoch: 30 days
I do not see anything wrong with the above scenario and it is quite possible in CarouselFactory.sol to create such epochs for Carousel.sol.

Also there is no document which states that there will be only 1 ongoing epoch at any given time but there is UI interaction flow which gives user option to select epoch for given token and strike price, [here step 3, 4, 5](https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/using-y2k#interacting-with-ui),  which makes it clear that UI/protocol has intention for multiple parallel epochs in single Carousel.sol.

Hence if you consider multiple epochs in progress in the same Carousel.sol then this is clearly a high severity bug.
I am open to provide more info if needed

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Not sure why this was excluded.
> Technically multiple epochs are possible for the same token and strike price aka same marketId in Carousel.sol.
> Consider this example:
> - Token: DAI, Strike price: 0.99 Epoch: 7 days
> - Token DAI, Strike price: 0.99 Epoch: 30 days
> I do not see anything wrong with the above scenario and it is quite possible in CarouselFactory.sol to create such epochs for Carousel.sol.
> 
> Also there is no document which states that there will be only 1 ongoing epoch at any given time but there is UI interaction flow which gives user option to select epoch for given token and strike price, [here step 3, 4, 5](https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/using-y2k#interacting-with-ui),  which makes it clear that UI/protocol has intention for multiple parallel epochs in single Carousel.sol.
> 
> Hence if you consider multiple epochs in progress in the same Carousel.sol then this is clearly a high severity bug.
> I am open to provide more info if needed

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KenzoAgada** [comment]
> Hence if you consider multiple epochs in progress in the same Carousel.sol

Note that in the chat it was mentioned that only one epoch is running at a time... This is probably why Carousel is designed with that assumption.
```"Yes, exactly there is only ever one epoch at a time running on the same market." - from DM```
[discord link](https://discord.com/channels/812037309376495636/1084853398240755833/1088661936452935700)

**Comment by dmitriia** [comment]
> 



> Technically multiple epochs are possible for the same token and strike price aka same marketId in Carousel.sol

You are right and Y2K does run weekly and monthly for some time in production. My understanding is that different Vaults are handling that, that differ in strikes, which are never the same for different timeframes. I.e. it is one pair of Vaults for weekly rolls and another, separate, pair for monthly rolls, and it is always one epoch for each pair.

**Comment by hrishibhat** [comment]
Escalation rejected

From the above comments this issue is based on a design assumption and since it is always one epoch for each pair the above issue is not valid

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> From the above comments this issue is based on a design assumption and since it is always one epoch for each pair the above issue is not valid

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
