### ISSUE TITLE
spyrosonic10 - Frontrunner get advantage to deposit all fund of in a specific epoch

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#354]
spyrosonic10

medium

# Frontrunner get advantage to deposit all fund of in a specific epoch

## Summary
There is a depositQueue where users will deposit funds when epochId is 0. User deposits fund this queue to use that fund for upcoming epochs.  Technically it is possible that two epochs exist at a time that have been created but not started yet and have overlapping deposit windows. `mintDepositInQueue` is a public method and anyone can call this method to deposit funds from the deposit queue to a specific epoch. Frontrunner may take advantage of this situation and deposit all funds in one specific epoch if he can profit from this situation.

## Vulnerability Detail
As mentioned in summary, the frontrunner may take advantage when more than one epoch has deposit windows open at a time.
This vulnerability may be more serious when a depositor of a counterparty calls `mintDepositInQueue` and deposits all funds of the queue in the epoch in which the frontrunner gets most advantage.

## Impact
Front runner takes advantage and moves the deposit queue's funds to a specific epoch.

## Code Snippet
[Carousel/Carousel.sol#L310-L355](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L310-L355)

## Tool used

Manual Review

## Recommendation
Consider implementation of the logic to handle front running problems in `mintDepositInQueue`. Also it can be beneficial to store user preference for epoch i.e. like to deposit in weekly epoch etc.

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC

Not sure why this was excluded.
Technically multiple epochs are possible for the same token and strike price aka same marketId in Carousel.sol.
Consider this example:
- Token: DAI, Strike price: 0.99 Epoch: 7 days
- Token DAI, Strike price: 0.99 Epoch: 30 days
I do not see anything wrong with the above scenario and it is quite possible in CarouselFactory.sol to create such epochs for Carousel.sol.

Also there is no document which states that there will be only 1 ongoing epoch at any given time but there is UI interaction flow which gives user option to select epoch for given token and strike price, [here step 3, 4, 5](https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/using-y2k#interacting-with-ui),  which makes it clear that UI/protocol has intention for multiple parallel epochs in single Carousel.sol.

Hence if you consider multiple epochs in progress in the same Carousel.sol then this is clearly a valid bug.
I am open to provide more info if needed

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Not sure why this was excluded.
> Technically multiple epochs are possible for the same token and strike price aka same marketId in Carousel.sol.
> Consider this example:
> - Token: DAI, Strike price: 0.99 Epoch: 7 days
> - Token DAI, Strike price: 0.99 Epoch: 30 days
> I do not see anything wrong with the above scenario and it is quite possible in CarouselFactory.sol to create such epochs for Carousel.sol.
> 
> Also there is no document which states that there will be only 1 ongoing epoch at any given time but there is UI interaction flow which gives user option to select epoch for given token and strike price, [here step 3, 4, 5](https://y2k-finance.gitbook.io/y2k-finance/how-to-guides/using-y2k#interacting-with-ui),  which makes it clear that UI/protocol has intention for multiple parallel epochs in single Carousel.sol.
> 
> Hence if you consider multiple epochs in progress in the same Carousel.sol then this is clearly a valid bug.
> I am open to provide more info if needed

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

From the above comments this issue is based on a design assumption and since it is always one epoch for each pair the above issue is not valid

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> From the above comments this issue is based on a design assumption and since it is always one epoch for each pair the above issue is not valid

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
