### ISSUE TITLE
Bauer - DOS attack to getRolloverTVL()

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#366]
Bauer

high

# DOS attack to getRolloverTVL()

## Summary
A bad actor can use the way that transfer his shares to another account to increase  the length of the array `rolloverQueue`. It can lead to out of gas and incorrect TVL.

## Vulnerability Detail
The ```enlistInRollover()``` function allows any user who has balance to enlists in rollover queue. To add a queue ,it require `balanceOf(_receiver, _epochId)  > _assets` and user has not queued up a rollover.It's easy to bypass. After user enlists in rollover queue,s/he can call the `safeTransferFrom()` to transfer the shares to another new account ,then contiune to enlists in rollover queue. A bad actor can increase the length of the array `rolloverQueue` in this way.
```solidity
function enlistInRollover(
        uint256 _epochId,
        uint256 _assets,
        address _receiver
    ) public epochIdExists(_epochId) minRequiredDeposit(_assets) {
        // check if sender is approved by owner
        if (
            msg.sender != _receiver &&
            isApprovedForAll(_receiver, msg.sender) == false
        ) revert OwnerDidNotAuthorize(msg.sender, _receiver);
        // check if user has enough balance
        if (balanceOf(_receiver, _epochId) < _assets)
            revert InsufficientBalance();

        // check if user has already queued up a rollover
        if (ownerToRollOverQueueIndex[_receiver] != 0) {
            // if so, update the queue
            uint256 index = getRolloverIndex(_receiver);
            rolloverQueue[index].assets = _assets;
            rolloverQueue[index].epochId = _epochId;
            return
        } else {
            // if not, add to queue
            rolloverQueue.push(
                QueueItem({
                    assets: _assets,
                    receiver: _receiver,
                    epochId: _epochId
                })
            );
            ownerToRollOverQueueIndex[_receiver] = rolloverQueue.length;

        }
        ownerToRollOverQueueIndex[_receiver] = rolloverQueue.length;

        emit RolloverQueued(_receiver, _assets, _epochId);
    }

```
The `getRolloverTVL()` function needs to calculated the TVL loop through the array `rolloverQueue.length`. As a result, when the list is too long, it will run out of gas. And the protocol will also return incorrect TVL data if the function works.
```solidity
function getRolloverTVL(uint256 _epochId)
        public
        view
        returns (uint256 tvl)
    {
        for (uint256 i = 0; i < rolloverQueue.length; i++) {
            if (
                rolloverQueue[i].epochId == _epochId &&
                (previewWithdraw(
                    rolloverQueue[i].epochId,
                    rolloverQueue[i].assets
                ) > rolloverQueue[i].assets)
            ) {
                tvl += rolloverQueue[i].assets;
            }
        }
    }
```

## Impact
The function getRolloverTVL() is not useful anymore when there is a DOS attack. And the protocol will also return incorrect TVL data if the function works.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L238-L271
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L655-L671
## Tool used

Manual Review

**Comment by dmitriia** [comment]
Invalid, cannot transferred due to `notRollingOver(from, id, amount)`:

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L196
