### ISSUE TITLE
Bauer - Users cannot use redundant emission shares

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#368]
Bauer

high

# Users cannot use redundant emission shares

## Summary
When the `burn()` function is called, the protocol only reduce the shares of vault, it iwll lead to  inconsistent data between the  shares of vault and  emission  shares.

## Vulnerability Detail
We can notice that the shares of vault and  emission shares are matched when mint ,`safeTransferFrom` and `_burn()`.However, if user call the function `NFT.burn()`,the protocol only reduce the shares of vault. It leads to inconsistent data between the two, confusing bookkeeping, and the emission shares will always be there.

## Impact
Confusing protocol bookkeeping,user will be not able to use  emission shares.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L190-L213
## Tool used

Manual Review

## Recommendation
Override the `burn()` function

**Comment by 3xHarry** [comment]
invalid issue, as `_burn` is an internal function and there is no burn function on openzeppelin implementation of 1155
