### ISSUE TITLE
VAD37 - Faulty set `whiteListAddress` if using same treasury address twice

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#399]
VAD37

medium

# Faulty set `whiteListAddress` if using same treasury address twice

## Summary

If timelock call update treasury to same address twice. The `whiteListAddress` will be set to false.

## Vulnerability Detail

Call `whiteListAddress` [from factory will flip true to false or false to true.](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultV2.sol#L258)

## Impact

Low. The event of timelock call update new treasury to same address again is really low.

If the worst happen. The vault paused and cannot call depeg or end epoch. Wait timelock for 3 days again

## Code Snippet

<https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultV2.sol#L256-L259>

## Tool used

Manual Review

## Recommendation

Change `whiteListAddress(address)` to `setWhiteListAddress(address,bool)` for clarity.

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/208
