### ISSUE TITLE
0x52 - Carousel#enlistInRollover fails to enforce share count limit when updating rollover

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#434]
0x52

medium

# Carousel#enlistInRollover fails to enforce share count limit when updating rollover

## Summary

Carousel#enlistInRollover fails to enforce share count limit when updating rollover. It checks if the user currently has enough shares but doesn't check that the user has enough shares to cover the new total. This can be used to permanently break rollovers.

## Vulnerability Detail

[Carousel.sol#L249-L258](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L249-L258)

        if (balanceOf(_receiver, _epochId) < _assets) <- audit-issue multiple deposits can bypass this check
            revert InsufficientBalance();

        // check if user has already queued up a rollover
        if (ownerToRollOverQueueIndex[_receiver] != 0) {
            // if so, update the queue
            uint256 index = getRolloverIndex(_receiver);
            rolloverQueue[index].assets = _assets;
            rolloverQueue[index].epochId = _epochId;
        } else {

When adding to a rollover position, the check only confirms that the user has enough assets to cover the amount of shares requested. It never checks that the user has enough shares to cover the new update amount. This can be used to break rollovers by making multiple requests to roll more shares than the user has because mintRollovers will revert when trying to burn them.

## Impact

Rollovers can be completely broken

## Code Snippet

[Carousel.sol#L238-L271](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L238-L271)

## Tool used

Manual Review

## Recommendation

When a user already has an open position check that they have enough shares to cover the new total

**Comment by IAm0x52** [comment]
Escalate for 10 USDC

This is valid. A user can create too big of a position and when it tries to burn too many shares rolling over will fail and be bricked
