### ISSUE TITLE
0xnirlin - No checks for the treasury and timelock in Factory(vaultFactory and carousalFactory) which can lead to costly redeploy.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#451]
0xnirlin

medium

# No checks for the treasury and timelock in Factory(vaultFactory and carousalFactory) which can lead to costly redeploy.

## Summary

There are no zero checks on deployment in constructor of both the `carousalFactory` and `vaultFactory` which could lead to costly redeploy.

## Vulnerability Detail

In `vaultFactory` at
[https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L37](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L37)
and in `carousalFactory`:
[https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/CarouselFactory.sol#L25](https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/CarouselFactory.sol#L25)
there are no checks in place for `timelock` to be `Address(0)` and there is no setter function to set the `timelock` after the deployment so if setted wrong on deployment have to redeploy the whole factory.

Same issue was reported in `uniswap V3 audit report` factory by trail of bits and was flagged `medium` so labelled it as medium here too.
Link to the report at : [https://github.com/Uniswap/v3-core/blob/main/audits/tob/audit.pdf](https://github.com/Uniswap/v3-core/blob/main/audits/tob/audit.pdf)

## Impact

Can lead to costly redeploy of the carousal factory and vault factory.

## Code Snippet

```solidity
    constructor(address _weth, address _treasury, address _timelocker) {
        if (_weth == address(0)) revert AddressZero();
        WETH = _weth;
        timelocker = _timelocker;
        treasury = _treasury; 
    }
```

```solidity

    constructor(
        address _weth,
        address _treasury,
        address _timelock,
        address _emissoinsToken
    ) VaultFactoryV2(_weth, _treasury, _timelock) {
        if (_emissoinsToken == address(0)) revert AddressZero();
        emissionsToken = IERC20(_emissoinsToken);
        //@audit-issue -med- same as factory - trail of bits reference not input validation to check treasury and timelock are not zero
    }
```

## Tool used

Manual Review

## Recommendation

1. Add zero check to the treasury and timelock in constructor.
2. Add a setter/changeTimelock function for the timelock and change of timelock should be a two step process.

**Comment by 3xHarry** [comment]
not really costly as we deploy on L2 but yes agree zero checks make sense

**Comment by dmitriia** [comment]
Low as no loss of funds and requires operator mistake

**Comment by 0xnirlin** [comment]
Escalate for 10 USDC

It look a valid medium issue to me for the following certain reason:
1. timelocker is immutable and no setter function so cannot change later on.
2. If missed the 0 check and time locker is set to 0 it leads to chain of problem.

Firstly here: 
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L214

You can never call the whitelist controller function second time and ever again.

Secondly:

There are certain function that only time locker function can call, and they will be never callable like following:

https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L228
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L253
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L275
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L286
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L310-L328

And same goes for the CarousalFactory contract functions:
https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/Carousel/CarouselFactory.sol#L163-L199

So eventually leading into redeployment and setting everything again from start leading to two outcome one is time wastage and secondly loss of credibility for the protocol

As dimitria mentioned about loss of funds, loss of funds is not the necessary criteria for medium finding.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> It look a valid medium issue to me for the following certain reason:
> 1. timelocker is immutable and no setter function so cannot change later on.
> 2. If missed the 0 check and time locker is set to 0 it leads to chain of problem.
> 
> Firstly here: 
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L214
> 
> You can never call the whitelist controller function second time and ever again.
> 
> Secondly:
> 
> There are certain function that only time locker function can call, and they will be never callable like following:
> 
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L228
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L253
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L275
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L286
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/VaultFactoryV2.sol#L310-L328
> 
> And same goes for the CarousalFactory contract functions:
> https://github.com/sherlock-audit/2023-03-Y2K/blob/93e3994dc0b0b944039050982957ebe2fa6ec599/Earthquake/src/v2/Carousel/CarouselFactory.sol#L163-L199
> 
> So eventually leading into redeployment and setting everything again from start leading to two outcome one is time wastage and secondly loss of credibility for the protocol
> 
> As dimitria mentioned about loss of funds, loss of funds is not the necessary criteria for medium finding.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Constructor input validation for addresses is not a valid high/medium

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> Constructor input validation for addresses is not a valid high/medium

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
