### ISSUE TITLE
ak1 - Carousel.sol, VaultV2.sol : critical functions like deposit, witdraw , safeTransferFrom function does not have pause/unpause protection in the event of emergency.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#454]
ak1

medium

# Carousel.sol, VaultV2.sol : critical functions like deposit, witdraw , safeTransferFrom function does not have pause/unpause protection in the event of emergency.

## Summary

Both `Carousel.sol`, and `VaultV2.sol`  contracts has withdraw, safeTrasnafeFrom and deposit functions.
User are allowed to interact with those function to deposit or withdraw or transfer the assets from one account to another account.
The functions are executed after certain predefined conditions are met, like `epochIdExists(_id)` , `epochHasEnded(_id)` , `nonReentrant` . 

none of the above mentioned function has the pause/unpause modifier.

## Vulnerability Detail

Refer the summary.

## Impact
In the event of emergency or hack, contract can not be halted for certain period of time till the issue is resolved.

One of the real life example is Thor chain attack. the team behind thorchain noticed an attack was going to occur well before the
system transferred funds to the hacker. However, they were not able to shut the system down fast enough.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultV2.sol#L93-L192

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L78-L180

## Tool used

Manual Review

## Recommendation

we suggest to add pause/unpause based modifier to protect the protocol from bad incidents.

**Comment by 3xHarry** [comment]
As balances in VaultV2 or Carousel are rather short-lived as created during the deposit window and burned after the epoch is settled. It would make no sense to add a pause modifier, as any admin-related functions need to be queued in the time locker which has a waiting period of a min 3 days which would be to long to stop any attack if such occurred. Users rely fully on the controller to settle the value of their VaultV2 holdings.

**Comment by dmitriia** [comment]
Design advice, closing as low.
Notice that y2k is intentionally left new markets creation and parameters to be permissioned, while the rest of the system is permissionless (depeg, closing, rolling can be run by anyone).
