### ISSUE TITLE
TrungOre - Incorrect treasury address was used in function `VaultFactoryV2.changeTreasury()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#88]
TrungOre

medium

# Incorrect treasury address was used in function `VaultFactoryV2.changeTreasury()`

## Summary
Function `VaultFactoryV2.changeTreasury` set the vault's treasury by using storage variable `treasury` instead of passing value `_treasury`
 
## Vulnerability Detail
Function `VaultFactoryV2.changeTreasury(_marketId, _treasury)` is used to whitelist `_treasury` and then set it as the treasury of vaults in `_marketId`.
```solidity=
/// url = https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L228-L246
function changeTreasury(uint256 _marketId, address _treasury)
    public
    onlyTimeLocker
{
    if (_treasury == address(0)) revert AddressZero();

    address[2] memory vaults = marketIdToVaults[_marketId];

    if (vaults[0] == address(0) || vaults[1] == address(0)) {
        revert MarketDoesNotExist(_marketId);
    }

    IVaultV2(vaults[0]).whiteListAddress(_treasury);
    IVaultV2(vaults[1]).whiteListAddress(_treasury);
    
    /// [$audit] use treasury instead of _treasury 
    IVaultV2(vaults[0]).setTreasury(treasury);
    IVaultV2(vaults[1]).setTreasury(treasury);

    emit AddressWhitelisted(_treasury, _marketId);
}
```
Unfortunately, the implementation has some typos when using `treasury` storage variable to pass in function `IVaultV2(vaults[0]).setTreasury(treasury)` after using passing value `_treasury` as parameter for the call `IVaultV2(vaults[]).whiteListAddress(_treasury)`

## Impact
Incorrect treasury is assigned for vault which makes the deposit fee sending to wrong address 

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L242-L243

## Tool used
Manual review 

## Recommendation
Modify function by using `_treasury` instead of `treasury` when calling `IVaultV2(vaults[]).setTreasury()`

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/435
