### ISSUE TITLE
roguereddwarf - Carousel: `getRolloverTVL` function returns ERC1155 balance instead of TVL

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#95]
roguereddwarf

medium

# Carousel: `getRolloverTVL` function returns ERC1155 balance instead of TVL

## Summary
The `Carousel.getRolloverTVL` function is supposed to return the total value locked in the rollover queue for a given `_epochId`.

The issue is that this function returns the wrong result.
It is supposed to return the total value locked, i.e. the underlying assets of the Vault. However it returns the ERC1155 vault tokens.

## Vulnerability Detail
The function just sums up the `assets` field of each queue item:
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L668

However 1 vault token might be worth e.g. 2 WETH.

The number of underlying tokens that `assets` is worth needs to be calculated as:
```solidity
previewWithdraw(
    rolloverQueue[i].epochId,
    rolloverQueue[i].assets
)
```

## Impact
The returned TVL is wrong which leads to wrong calculations in any components relying on this function.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L655-L671

## Tool used
Manual Review

## Recommendation
Fix:
```diff
diff --git a/Earthquake/src/v2/Carousel/Carousel.sol b/Earthquake/src/v2/Carousel/Carousel.sol
index ed460af..44fcdae 100644
--- a/Earthquake/src/v2/Carousel/Carousel.sol
+++ b/Earthquake/src/v2/Carousel/Carousel.sol
@@ -665,7 +665,7 @@ contract Carousel is VaultV2 {
                     rolloverQueue[i].assets
                 ) > rolloverQueue[i].assets)
             ) {
-                tvl += rolloverQueue[i].assets;
+                tvl += previewWithdraw(rolloverQueue[i].epochId,rolloverQueue[i].assets);
             }
         }
     }
```

**Comment by 3xHarry** [comment]
great catch

**Comment by VAD37** [comment]
Escalate for 11 USDC

Give these guys some love too.

Duplicate of:
[roguereddwarf	069	medium	L-view function wrong	Carousel: DOS in `getRolloverTVL` and `getDepositQueueTVL` function](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/69)

[ShadowForce	313	medium	L-view function wrong	unbounded loop in view function leads to a dos](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/313)

[Bauer	332	medium	L-view function wrong	DOS attack to getDepositQueueTVL()](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/332)

**Comment by sherlock-admin** [comment]
> Escalate for 11 USDC
> 
> Give these guys some love too.
> 
> Duplicate of:
> [roguereddwarf	069	medium	L-view function wrong	Carousel: DOS in `getRolloverTVL` and `getDepositQueueTVL` function](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/69)
> 
> [ShadowForce	313	medium	L-view function wrong	unbounded loop in view function leads to a dos](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/313)
> 
> [Bauer	332	medium	L-view function wrong	DOS attack to getDepositQueueTVL()](https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/332)

You've created an escalation for 11 USDC, however, the escalation amount is fixed at 10 USDC.
To update the escalation with the correct amount, please edit this comment. **(do not create a new comment)**

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by RobocopSR** [comment]
Escalate for 10 USDC

Although I agree on this being an excellent finding, from Sherlock docs this is a valid low issue but not medium:

"Incorrect values in View functions are by default considered low. 
Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact."

In the codebase the function `getRolloverTVL(uint256 _epochId)` is not used anywhere

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Although I agree on this being an excellent finding, from Sherlock docs this is a valid low issue but not medium:
> 
> "Incorrect values in View functions are by default considered low. 
> Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact."
> 
> In the codebase the function `getRolloverTVL(uint256 _epochId)` is not used anywhere

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid low
> 
> 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
