### ISSUE TITLE
roguereddwarf - Carousel: admin role can steal user collateral from deposit queue and rollover queue even though admin should not be able to

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-Y2K-judging#96]
roguereddwarf

medium

# Carousel: admin role can steal user collateral from deposit queue and rollover queue even though admin should not be able to

## Summary
According to the contest page the "admin" role should not be able to steal user funds:
![2023-03-20_11-44](https://user-images.githubusercontent.com/118631472/226323586-c01fa0e7-2016-4d1e-8fe8-34e622442543.png)

The issue is caused because the admin can create epochs with arbitrary `epochBegin` and `epochEnd` timestamps.

## Vulnerability Detail
The admin can choose these timestamps as close together as possible.
The closest together is `epochBegin = block.timestamp` and `epochEnd = block.timestamp + 1`.

The admin can then mint all pending deposits in the premium vault and rollover all assets in the premium vault and then take the opposite position in the collateral vault with a very small deposit.

Assuming that 
a) there are no bots in place to monitor for this kind of attack and to make immediate deposits to the collateral vault
b) within the 1 second between `epochBegin` and `epochEnd` there is no depeg

the admin then receives all the funds from the deposit queue and rollover queue that are in the premium vault.

## Impact
The admin can steal user funds even though the sponsor said in the contest page that the admin role should not be able to do this.

## Code Snippet
https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/VaultFactoryV2.sol#L137-L169

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L310-L355

https://github.com/sherlock-audit/2023-03-Y2K/blob/main/Earthquake/src/v2/Carousel/Carousel.sol#L361-L459

## Tool used
Manual Review

## Recommendation
I recommend to introduce a minimum time between epoch creation and epoch start and between epoch start and epoch end.
E.g. 3 days for both timespans.
This minimum time delay might also be changeable by the timelock.

This allows for sufficient time for users to deposit into the vaults.
If the admin tried to perform the attack other users will deposit into the collateral vault and the admin will only receive his fair share as a regular user.

**Comment by dmitriia** [comment]
Duplicate https://github.com/sherlock-audit/2023-03-Y2K-judging/issues/375

**Comment by roguereddwarf** [comment]
Escalate for 10 USDC

This is not a duplicate of #375.

#375 talks about a misconfiguration that I agree does not have an impact.

However this finding talks about how the admin role can steal user funds. This should be medium severity as the impact is the same as other medium severity issues: #47

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is not a duplicate of #375.
> 
> #375 talks about a misconfiguration that I agree does not have an impact.
> 
> However this finding talks about how the admin role can steal user funds. This should be medium severity as the impact is the same as other medium severity issues: #47 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Admin is trusted to configure epochs.
Also #47 is considered low

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Admin is trusted to configure epochs.
> Also #47 is also considered low

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
